name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install
        run: yarn install

      - name: ls utils
        run: ls ./packages/utils

      - name: ls components-react
        run: ls ./packages/components-react/packages/constants

      - name: Test
        run: yarn start
