name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      - name: Install
        run: yarn install

      - name: ls
        run: ls ./packages/utils

      - name: Test
        run: yarn start
